import { fromTypes, openapi } from "@elysiajs/openapi";
import { t } from "elysia";

const userModel = t.Object(
  {
    id: t.String(),
    firebaseUid: t.String(),
    phoneNumber: t.Optional(t.String()),
    email: t.Optional(t.String()),
    fullName: t.Optional(t.String()),
    typeUser: t.Optional(t.String()),
    status: t.Optional(t.String()),
    createdAt: t.String({ format: "date-time" }),
    updatedAt: t.Optional(t.String({ format: "date-time" })),
  },
  { description: "User information payload returned from SuperApp services" }
);

const errorResponseModel = t.Object(
  {
    success: t.Boolean(),
    message: t.String(),
    errors: t.Optional(t.Array(t.Unknown())),
  },
  { description: "Standard error response envelope used across SuperApp APIs" }
);

const authenticatedProfileResponseModel = t.Object(
  {
    success: t.Boolean(),
    data: t.Object({
      user: userModel,
    }),
  },
  { description: "Authenticated user profile response payload" }
);

const serverUrl = process.env.BASE_URL ?? `localhost:${Number(process.env.PORT ?? 8080)}`;

export const openapiConfig = openapi({
  documentation: {
    info: {
      title: "SuperApp API",
      description: "API documentation for SuperApp backend services",
      version: "1.0.0",
    },
    servers: [
      {
        url: serverUrl,
        description: "Local development server",
      },
    ],
    tags: [
      {
        name: "Authentication",
        description: "Authentication and authorization endpoints",
      },
      {
        name: "User Management",
        description: "User profile and administration operations",
      },
      {
        name: "Charge Point",
        description: "Charging station provisioning and commands",
      },
      {
        name: "Tax Invoice Profile",
        description: "Tax invoice profile management for users",
      },
      {
        name: "Health",
        description: "Service readiness and monitoring probes",
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
          description:
            "Include JWT access token generated by /api/auth/login in the Authorization header",
        },
      },
    },
  },
  references: fromTypes("src/app.ts"),
});

export const models = {
  User: userModel,
  ErrorResponse: errorResponseModel,
  AuthenticatedProfileResponse: authenticatedProfileResponseModel,
};