import { cors } from '@elysiajs/cors';
import { jwt } from '@elysiajs/jwt';
import { fromTypes, openapi } from '@elysiajs/openapi';
import { Elysia, t } from 'elysia';
import { prisma } from './lib/prisma';
import { serviceContainer } from './services';

// Get services from container
const { jwtService } = serviceContainer;

const port = Number(process.env.PORT ?? 8080);
const serverUrl = process.env.BASE_URL ?? `http://localhost:${port}`;

const userModel = t.Object({
  id: t.String(),
  firebaseUid: t.String(),
  phoneNumber: t.Optional(t.String()),
  email: t.Optional(t.String()),
  fullName: t.Optional(t.String()),
  typeUser: t.Optional(t.String()),
  status: t.Optional(t.String()),
  createdAt: t.String({ format: 'date-time' }),
  updatedAt: t.Optional(t.String({ format: 'date-time' }))
}, { description: 'User information payload returned from SuperApp services' });

const errorResponseModel = t.Object({
  success: t.Boolean(),
  message: t.String(),
  errors: t.Optional(t.Array(t.Unknown()))
}, { description: 'Standard error response envelope used across SuperApp APIs' });

const authenticatedProfileResponseModel = t.Object({
  success: t.Boolean(),
  data: t.Object({
    user: userModel
  })
}, { description: 'Authenticated user profile response payload' });

export const app = new Elysia()
  .use(cors())
  .model({
    User: userModel,
    ErrorResponse: errorResponseModel,
    AuthenticatedProfileResponse: authenticatedProfileResponseModel
  })
  .use(openapi({
    documentation: {
      info: {
        title: 'SuperApp API',
        description: 'API documentation for SuperApp backend services',
        version: '1.0.0'
      },
      servers: [
        {
          url: serverUrl,
          description: 'Local development server'
        }
      ],
      tags: [
        { name: 'Authentication', description: 'Authentication and authorization endpoints' },
        { name: 'User Management', description: 'User profile and administration operations' },
        { name: 'Charge Point', description: 'Charging station provisioning and commands' },
        { name: 'Health', description: 'Service readiness and monitoring probes' }
      ],
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT',
            description: 'Include JWT access token generated by /api/auth/login in the Authorization header'
          }
        }
      }
    },
    references: fromTypes('src/app.ts')
  }))
  .use(jwt({
    name: 'jwt',
    secret: process.env.JWT_SECRET || 'your-secret-key'
  }))
  .use(serviceContainer.getAuthController())
  .use(serviceContainer.getUserController())
  .use(serviceContainer.getChargePointController())
  .derive(async ({ request, set }: { request: Request; set: any }) => {
    const authHeader = request.headers.get('authorization');
    
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return {
        user: null
      };
    }

    const token = authHeader.substring(7);
      console.log("check verify",token)
    const payload = await jwtService.verifyToken(token);
    console.log("check payload",payload)
    if (!payload) {
      return {
        user: null
      };
    }

    // Fetch user from database to ensure they still exist and are active
    const user = await prisma.user.findUnique({
      where: { id: payload.userId },
      select: {
        id: true,
        phoneNumber: true,
        status: true,
        typeUser: true,
        createdAt: true
      }
    });

    if (!user || user.status !== 'ACTIVE') {
      return {
        user: null
      };
    }

    return {
      user
    };
  })
  .guard(
    ({ user }: any) => !!user,
    (app: any) =>
      app.get('/api/profile', ({ user }: any) => {
        return {
          success: true,
          data: {
            user
          }
        };
      }, {
        detail: {
          tags: ['User Management'],
          summary: 'Retrieve authenticated user profile',
          description: 'Returns the profile information for the user associated with the provided bearer token.',
          security: [
            {
              bearerAuth: []
            }
          ],
          responses: {
            200: {
              description: 'Profile information successfully retrieved',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/AuthenticatedProfileResponse' }
                }
              }
            },
            401: {
              description: 'Missing or invalid bearer token',
              content: {
                'application/json': {
                  schema: { $ref: '#/components/schemas/ErrorResponse' }
                }
              }
            }
          }
        }
      })
  )
  .get('/health', () => ({
    status: 'ok',
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
    version: '1.0.0',
    environment: process.env.NODE_ENV || 'development'
  }), {
    detail: {
      tags: ['Health'],
      summary: '🏥 Health Check',
      description: 'Returns the current status and health information of the API server',
      responses: {
        200: {
          description: 'Server is healthy',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  status: { type: 'string', example: 'ok' },
                  timestamp: { type: 'string', format: 'date-time' },
                  uptime: { type: 'number', description: 'Server uptime in seconds' },
                  version: { type: 'string', example: '1.0.0' },
                  environment: { type: 'string', example: 'development' }
                }
              }
            }
          }
        }
      }
    }
  })
  .onError(({ code, error, set }: { code: any; error: any; set: any }) => {
    switch (code) {
      case 'VALIDATION':
        set.status = 400;
        return {
          success: false,
          message: 'Invalid input data',
          errors: error.all
        };
      case 'NOT_FOUND':
        set.status = 404;
        return {
          success: false,
          message: 'Resource not found'
        };
      case 'INTERNAL_SERVER_ERROR':
        set.status = 500;
        return {
          success: false,
          message: 'Internal server error'
        };
      default:
        set.status = 500;
        return {
          success: false,
          message: 'An unexpected error occurred'
        };
    }
  });

app.listen(port, () => {
  console.log(`🦊 Server is running on port ${port}`);
  console.log(`📚 OpenAPI Documentation: ${serverUrl}/openapi`);
  console.log(`📄 OpenAPI Schema: ${serverUrl}/openapi/json`);
  console.log(`📝 API Endpoints:`);
  console.log(`   POST /api/auth/register - User registration`);
  console.log(`   POST /api/auth/login - User login`);
  console.log(`   POST /api/auth/refresh - Refresh token`);
  console.log(`   GET /api/profile - Get user profile (protected)`);
  console.log(`   GET /health - Health check`);
});
