#!/usr/bin/env bun
/**
 * Script สร้างสถานี (Station) และ Charge Points สำหรับ SuperApp
 *
 * การใช้งาน:
 * bun scripts/create-stations.ts
 *
 * Environment variables ที่ต้องการ:
 * - DATABASE_URL: URL สำหรับเชื่อมต่อฐานข้อมูล PostgreSQL
 */

import {
  AdminStationService,
  CreateStationData
} from "../src/admin/station/station.service";
import { prisma } from "../src/lib/prisma";

// ข้อมูลสถานีตัวอย่าง
const sampleStations: CreateStationData[] = [
  {
    stationname: "สถานีชาร์จ Siam Paragon",
    location: "สยามพารากอน กรุงเทพฯ",
    latitude: 13.7465,
    longitude: 100.535,
    imageUrl: "https://example.com/images/siam-paragon.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 15.0,
    onPeakRate: 20.0,
    onPeakStartTime: "17:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 25.0,
    offPeakRate: 12.0,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 15.0,
    chargePoints: [
      {
        chargepointname: "SP-CP-001",
        chargePointIdentity: "TH-SIAM-SP001",
        chargePointModel: "EV Charger Pro 22kW",
        chargePointVendor: "ChargeTech",
        serialNumber: "CTSP001234",
        powerRating: 22.0,
        connectorCount: 2,
        brand: "ChargeTech",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
      {
        chargepointname: "SP-CP-002",
        chargePointIdentity: "TH-SIAM-SP002",
        chargePointModel: "Fast Charger 50kW",
        chargePointVendor: "PowerCharge",
        serialNumber: "PCSP002345",
        powerRating: 50.0,
        connectorCount: 1,
        brand: "PowerCharge",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Central World",
    location: "เซ็นทรัลเวิลด์ กรุงเทพฯ",
    latitude: 13.747,
    longitude: 100.5404,
    imageUrl: "https://example.com/images/central-world.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 18.0,
    onPeakRate: 25.0,
    onPeakStartTime: "17:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 30.0,
    offPeakRate: 15.0,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 18.0,
    chargePoints: [
      {
        chargepointname: "CW-CP-001",
        chargePointIdentity: "TH-CENTRAL-CW001",
        chargePointModel: "Ultra Charger 150kW",
        chargePointVendor: "SuperCharge",
        serialNumber: "SCCW001789",
        powerRating: 150.0,
        connectorCount: 2,
        brand: "SuperCharge",
        protocol: "OCPP20" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Terminal 21 Asok",
    location: "เทอร์มินัล 21 อโศก กรุงเทพฯ",
    latitude: 13.7478,
    longitude: 100.5595,
    imageUrl: "https://example.com/images/terminal21.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 16.0,
    onPeakRate: 22.0,
    onPeakStartTime: "17:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 28.0,
    offPeakRate: 13.0,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 16.0,
    chargePoints: [
      {
        chargepointname: "T21-CP-001",
        chargePointIdentity: "TH-T21-ASOK001",
        chargePointModel: "Standard Charger 7kW",
        chargePointVendor: "EcoCharge",
        serialNumber: "ECT2101234",
        powerRating: 7.0,
        connectorCount: 4,
        brand: "EcoCharge",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ MBK Center",
    location: "เอ็มบีเค เซ็นเตอร์ กรุงเทพฯ",
    latitude: 13.7441,
    longitude: 100.5297,
    imageUrl: "https://example.com/images/mbk.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 14.5,
    onPeakRate: 19.5,
    onPeakStartTime: "17:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 24.5,
    offPeakRate: 11.5,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 14.5,
    chargePoints: [
      {
        chargepointname: "MBK-CP-001",
        chargePointIdentity: "TH-MBK-001",
        chargePointModel: "Smart Charger 11kW",
        chargePointVendor: "TechCharge",
        serialNumber: "TCMBK001456",
        powerRating: 11.0,
        connectorCount: 2,
        brand: "TechCharge",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Chatuchak Weekend Market",
    location: "ตลาดนัดจตุจักร กรุงเทพฯ",
    latitude: 13.7991,
    longitude: 100.5491,
    imageUrl: "https://example.com/images/chatuchak.jpg",
    openclosedays: "เสาร์-อาทิตย์ 06:00-18:00",
    flatRate: 12.0,
    onPeakRate: 16.0,
    onPeakStartTime: "10:00",
    onPeakEndTime: "14:00",
    onPeakbaseRate: 20.0,
    offPeakRate: 10.0,
    offPeakStartTime: "06:00",
    offPeakEndTime: "10:00",
    offPeakbaseRate: 12.0,
    chargePoints: [
      {
        chargepointname: "JJ-CP-001",
        chargePointIdentity: "TH-JJ-MARKET001",
        chargePointModel: "Outdoor Charger 7kW",
        chargePointVendor: "WeatherProof",
        serialNumber: "WPJJ001234",
        powerRating: 7.0,
        connectorCount: 6,
        brand: "WeatherProof",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Don Mueang Airport",
    location: "ท่าอากาศยานดอนเมือง กรุงเทพฯ",
    latitude: 13.9094,
    longitude: 100.6066,
    imageUrl: "https://example.com/images/donmueang.jpg",
    openclosedays: "24/7",
    flatRate: 25.0,
    onPeakRate: 35.0,
    onPeakStartTime: "06:00",
    onPeakEndTime: "22:00",
    onPeakbaseRate: 40.0,
    offPeakRate: 20.0,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 25.0,
    chargePoints: [
      {
        chargepointname: "DMK-CP-001",
        chargePointIdentity: "TH-DMK-AIRPORT001",
        chargePointModel: "Airport Rapid Charger 100kW",
        chargePointVendor: "AirportTech",
        serialNumber: "ATDMK001999",
        powerRating: 100.0,
        connectorCount: 4,
        brand: "AirportTech",
        protocol: "OCPP20" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
      {
        chargepointname: "DMK-CP-002",
        chargePointIdentity: "TH-DMK-AIRPORT002",
        chargePointModel: "Fast Charger 60kW",
        chargePointVendor: "TravelCharge",
        serialNumber: "TCDMK002111",
        powerRating: 60.0,
        connectorCount: 2,
        brand: "TravelCharge",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Big C Ratchadamri",
    location: "บิ๊กซี ราชดำริ กรุงเทพฯ",
    latitude: 13.7414,
    longitude: 100.5378,
    imageUrl: "https://example.com/images/bigc-ratchadamri.jpg",
    openclosedays: "จันทร์-อาทิตย์ 09:00-23:00",
    flatRate: 13.5,
    onPeakRate: 18.5,
    onPeakStartTime: "17:00",
    onPeakEndTime: "20:00",
    onPeakbaseRate: 23.0,
    offPeakRate: 11.0,
    offPeakStartTime: "23:00",
    offPeakEndTime: "07:00",
    offPeakbaseRate: 13.5,
    chargePoints: [
      {
        chargepointname: "BIGC-CP-001",
        chargePointIdentity: "TH-BIGC-RD001",
        chargePointModel: "Retail Charger 22kW",
        chargePointVendor: "RetailPower",
        serialNumber: "RPBIGC001567",
        powerRating: 22.0,
        connectorCount: 3,
        brand: "RetailPower",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Emporium Shopping Center",
    location: "ดิ เอ็มโพเรี่ยม กรุงเทพฯ",
    latitude: 13.7307,
    longitude: 100.5698,
    imageUrl: "https://example.com/images/emporium.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 22.0,
    onPeakRate: 30.0,
    onPeakStartTime: "17:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 35.0,
    offPeakRate: 18.0,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 22.0,
    chargePoints: [
      {
        chargepointname: "EMP-CP-001",
        chargePointIdentity: "TH-EMP-LUXURY001",
        chargePointModel: "Premium Charger 75kW",
        chargePointVendor: "LuxuryCharge",
        serialNumber: "LCEMP001888",
        powerRating: 75.0,
        connectorCount: 2,
        brand: "LuxuryCharge",
        protocol: "OCPP20" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Lumpini Park",
    location: "สวนลุมพินี กรุงเทพฯ",
    latitude: 13.7314,
    longitude: 100.5429,
    imageUrl: "https://example.com/images/lumpini-park.jpg",
    openclosedays: "จันทร์-อาทิตย์ 05:00-20:00",
    flatRate: 10.0,
    onPeakRate: 14.0,
    onPeakStartTime: "17:00",
    onPeakEndTime: "19:00",
    onPeakbaseRate: 18.0,
    offPeakRate: 8.0,
    offPeakStartTime: "20:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 10.0,
    chargePoints: [
      {
        chargepointname: "LP-CP-001",
        chargePointIdentity: "TH-LUMPINI-PARK001",
        chargePointModel: "Eco Park Charger 7kW",
        chargePointVendor: "GreenPark",
        serialNumber: "GPLP001234",
        powerRating: 7.0,
        connectorCount: 8,
        brand: "GreenPark",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
      {
        chargepointname: "LP-CP-002",
        chargePointIdentity: "TH-LUMPINI-PARK002",
        chargePointModel: "Solar Charger 11kW",
        chargePointVendor: "SolarTech",
        serialNumber: "STLP002456",
        powerRating: 11.0,
        connectorCount: 4,
        brand: "SolarTech",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Mega Bangna",
    location: "เมกาบางนา กรุงเทพฯ",
    latitude: 13.6676,
    longitude: 100.6216,
    imageUrl: "https://example.com/images/mega-bangna.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 15.5,
    onPeakRate: 21.0,
    onPeakStartTime: "17:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 26.0,
    offPeakRate: 12.5,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 15.5,
    chargePoints: [
      {
        chargepointname: "MB-CP-001",
        chargePointIdentity: "TH-MEGA-BANGNA001",
        chargePointModel: "Mall Charger 44kW",
        chargePointVendor: "MallPower",
        serialNumber: "MPMB001333",
        powerRating: 44.0,
        connectorCount: 6,
        brand: "MallPower",
        protocol: "OCPP20" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Future Park Rangsit",
    location: "ฟิวเจอร์ พาร์ค รังสิต ปทุมธานี",
    latitude: 13.9636,
    longitude: 100.6247,
    imageUrl: "https://example.com/images/future-park.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 13.0,
    onPeakRate: 17.5,
    onPeakStartTime: "18:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 22.0,
    offPeakRate: 10.5,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 13.0,
    chargePoints: [
      {
        chargepointname: "FP-CP-001",
        chargePointIdentity: "TH-FUTURE-PARK001",
        chargePointModel: "Suburban Charger 30kW",
        chargePointVendor: "SuburbanPower",
        serialNumber: "SPFP001777",
        powerRating: 30.0,
        connectorCount: 4,
        brand: "SuburbanPower",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ IKEA Bang Yai",
    location: "อิเกีย บางใหญ่ นนทบุรี",
    latitude: 13.8761,
    longitude: 100.4086,
    imageUrl: "https://example.com/images/ikea-bangyai.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 14.0,
    onPeakRate: 19.0,
    onPeakStartTime: "17:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 24.0,
    offPeakRate: 11.0,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 14.0,
    chargePoints: [
      {
        chargepointname: "IKEA-CP-001",
        chargePointIdentity: "TH-IKEA-BANGYAI001",
        chargePointModel: "Nordic Charger 22kW",
        chargePointVendor: "NordicPower",
        serialNumber: "NPIKEA001555",
        powerRating: 22.0,
        connectorCount: 8,
        brand: "NordicPower",
        protocol: "OCPP20" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
      {
        chargepointname: "IKEA-CP-002",
        chargePointIdentity: "TH-IKEA-BANGYAI002",
        chargePointModel: "Eco Home Charger 11kW",
        chargePointVendor: "HomeCharge",
        serialNumber: "HCIKEA002666",
        powerRating: 11.0,
        connectorCount: 6,
        brand: "HomeCharge",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Central Ladprao",
    location: "เซ็นทรัล ลาดพร้าว กรุงเทพฯ",
    latitude: 13.8198,
    longitude: 100.5602,
    imageUrl: "https://example.com/images/central-ladprao.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 16.5,
    onPeakRate: 22.5,
    onPeakStartTime: "17:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 27.0,
    offPeakRate: 13.5,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 16.5,
    chargePoints: [
      {
        chargepointname: "CLP-CP-001",
        chargePointIdentity: "TH-CENTRAL-LADPRAO001",
        chargePointModel: "Urban Charger 50kW",
        chargePointVendor: "UrbanTech",
        serialNumber: "UTCLP001444",
        powerRating: 50.0,
        connectorCount: 3,
        brand: "UrbanTech",
        protocol: "OCPP20" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ The Mall Bangkae",
    location: "เดอะมอลล์ บางแค กรุงเทพฯ",
    latitude: 13.7036,
    longitude: 100.4044,
    imageUrl: "https://example.com/images/the-mall-bangkae.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 13.5,
    onPeakRate: 18.0,
    onPeakStartTime: "17:30",
    onPeakEndTime: "20:30",
    onPeakbaseRate: 23.0,
    offPeakRate: 10.5,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 13.5,
    chargePoints: [
      {
        chargepointname: "TMB-CP-001",
        chargePointIdentity: "TH-THEMALL-BANGKAE001",
        chargePointModel: "Community Charger 15kW",
        chargePointVendor: "CommunityPower",
        serialNumber: "CPTMB001222",
        powerRating: 15.0,
        connectorCount: 5,
        brand: "CommunityPower",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Gateway Ekamai",
    location: "เกตเวย์ เอกมัย กรุงเทพฯ",
    latitude: 13.7267,
    longitude: 100.5851,
    imageUrl: "https://example.com/images/gateway-ekamai.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 17.0,
    onPeakRate: 23.5,
    onPeakStartTime: "17:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 28.5,
    offPeakRate: 14.0,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 17.0,
    chargePoints: [
      {
        chargepointname: "GW-CP-001",
        chargePointIdentity: "TH-GATEWAY-EKAMAI001",
        chargePointModel: "Transit Charger 35kW",
        chargePointVendor: "TransitTech",
        serialNumber: "TTGW001888",
        powerRating: 35.0,
        connectorCount: 4,
        brand: "TransitTech",
        protocol: "OCPP20" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
      {
        chargepointname: "GW-CP-002",
        chargePointIdentity: "TH-GATEWAY-EKAMAI002",
        chargePointModel: "Express Charger 60kW",
        chargePointVendor: "ExpressCharge",
        serialNumber: "ECGW002999",
        powerRating: 60.0,
        connectorCount: 2,
        brand: "ExpressCharge",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Saphan Phut Night Market",
    location: "ตลาดสะพานพุท กรุงเทพฯ",
    latitude: 13.7346,
    longitude: 100.5052,
    imageUrl: "https://example.com/images/saphan-phut.jpg",
    openclosedays: "จันทร์-อาทิตย์ 18:00-24:00",
    flatRate: 11.0,
    onPeakRate: 15.0,
    onPeakStartTime: "19:00",
    onPeakEndTime: "23:00",
    onPeakbaseRate: 19.0,
    offPeakRate: 9.0,
    offPeakStartTime: "00:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 11.0,
    chargePoints: [
      {
        chargepointname: "SP-CP-001",
        chargePointIdentity: "TH-SAPHANPHUT-001",
        chargePointModel: "Night Market Charger 7kW",
        chargePointVendor: "NightCharge",
        serialNumber: "NCSP001123",
        powerRating: 7.0,
        connectorCount: 10,
        brand: "NightCharge",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Klong Toey Port",
    location: "ท่าเรือคลองเตย กรุงเทพฯ",
    latitude: 13.7167,
    longitude: 100.5539,
    imageUrl: "https://example.com/images/klong-toey-port.jpg",
    openclosedays: "24/7",
    flatRate: 20.0,
    onPeakRate: 28.0,
    onPeakStartTime: "06:00",
    onPeakEndTime: "18:00",
    onPeakbaseRate: 32.0,
    offPeakRate: 16.0,
    offPeakStartTime: "18:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 20.0,
    chargePoints: [
      {
        chargepointname: "KT-CP-001",
        chargePointIdentity: "TH-KLONGTOEY-PORT001",
        chargePointModel: "Industrial Charger 120kW",
        chargePointVendor: "IndustrialPower",
        serialNumber: "IPKT001777",
        powerRating: 120.0,
        connectorCount: 6,
        brand: "IndustrialPower",
        protocol: "OCPP20" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
      {
        chargepointname: "KT-CP-002",
        chargePointIdentity: "TH-KLONGTOEY-PORT002",
        chargePointModel: "Heavy Duty Charger 80kW",
        chargePointVendor: "HeavyDuty",
        serialNumber: "HDKT002888",
        powerRating: 80.0,
        connectorCount: 4,
        brand: "HeavyDuty",
        protocol: "OCPP20" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Samyan Mitrtown",
    location: "สามย่าน มิตรทาวน์ กรุงเทพฯ",
    latitude: 13.7312,
    longitude: 100.5295,
    imageUrl: "https://example.com/images/samyan-mitrtown.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 18.5,
    onPeakRate: 25.0,
    onPeakStartTime: "17:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 30.0,
    offPeakRate: 15.0,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 18.5,
    chargePoints: [
      {
        chargepointname: "SMT-CP-001",
        chargePointIdentity: "TH-SAMYAN-MITR001",
        chargePointModel: "Smart City Charger 40kW",
        chargePointVendor: "SmartCity",
        serialNumber: "SCSMT001456",
        powerRating: 40.0,
        connectorCount: 6,
        brand: "SmartCity",
        protocol: "OCPP20" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Robinson Lifestyle Center Ratchapruek",
    location: "โรบินสัน ไลฟ์สไตล์ เซ็นเตอร์ ราชพฤกษ์ นนทบุรี",
    latitude: 13.8112,
    longitude: 100.3954,
    imageUrl: "https://example.com/images/robinson-ratchapruek.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 14.5,
    onPeakRate: 19.5,
    onPeakStartTime: "17:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 24.0,
    offPeakRate: 11.5,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 14.5,
    chargePoints: [
      {
        chargepointname: "RB-CP-001",
        chargePointIdentity: "TH-ROBINSON-RP001",
        chargePointModel: "Lifestyle Charger 25kW",
        chargePointVendor: "LifestylePower",
        serialNumber: "LPRB001369",
        powerRating: 25.0,
        connectorCount: 5,
        brand: "LifestylePower",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Tesco Lotus Ramkhamhaeng",
    location: "เทสโก้ โลตัส รามคำแหง กรุงเทพฯ",
    latitude: 13.7644,
    longitude: 100.6094,
    imageUrl: "https://example.com/images/tesco-ramkhamhaeng.jpg",
    openclosedays: "จันทร์-อาทิตย์ 08:00-23:00",
    flatRate: 12.5,
    onPeakRate: 17.0,
    onPeakStartTime: "17:00",
    onPeakEndTime: "20:00",
    onPeakbaseRate: 21.5,
    offPeakRate: 9.5,
    offPeakStartTime: "23:00",
    offPeakEndTime: "07:00",
    offPeakbaseRate: 12.5,
    chargePoints: [
      {
        chargepointname: "TL-CP-001",
        chargePointIdentity: "TH-TESCO-RAMKAM001",
        chargePointModel: "Supermarket Charger 18kW",
        chargePointVendor: "MarketPower",
        serialNumber: "MPTL001258",
        powerRating: 18.0,
        connectorCount: 7,
        brand: "MarketPower",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
  {
    stationname: "สถานีชาร์จ Fashion Island",
    location: "แฟชั่น ไอส์แลนด์ กรุงเทพฯ",
    latitude: 13.8833,
    longitude: 100.5833,
    imageUrl: "https://example.com/images/fashion-island.jpg",
    openclosedays: "จันทร์-อาทิตย์ 10:00-22:00",
    flatRate: 19.0,
    onPeakRate: 26.0,
    onPeakStartTime: "17:00",
    onPeakEndTime: "21:00",
    onPeakbaseRate: 31.0,
    offPeakRate: 15.5,
    offPeakStartTime: "22:00",
    offPeakEndTime: "06:00",
    offPeakbaseRate: 19.0,
    chargePoints: [
      {
        chargepointname: "FI-CP-001",
        chargePointIdentity: "TH-FASHION-ISLAND001",
        chargePointModel: "Fashion Charger 45kW",
        chargePointVendor: "FashionTech",
        serialNumber: "FTFI001789",
        powerRating: 45.0,
        connectorCount: 4,
        brand: "FashionTech",
        protocol: "OCPP20" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
      {
        chargepointname: "FI-CP-002",
        chargePointIdentity: "TH-FASHION-ISLAND002",
        chargePointModel: "Luxury Mall Charger 30kW",
        chargePointVendor: "LuxuryMall",
        serialNumber: "LMFI002147",
        powerRating: 30.0,
        connectorCount: 3,
        brand: "LuxuryMall",
        protocol: "OCPP16" as any,
        organization_id: "c3dac355-3cbe-412f-a509-4901f58f8bee",
      },
    ],
  },
];

async function main() {
  console.log("🚀 เริ่มต้นสร้างสถานีชาร์จและ Charge Points...");

  try {
    // ตรวจสอบการเชื่อมต่อฐานข้อมูล
    await prisma.$connect();
    console.log("✅ เชื่อมต่อฐานข้อมูลสำเร็จ");

    // สร้าง Station Service
    const stationService = new AdminStationService();

    let totalStationsCreated = 0;
    let totalChargePointsCreated = 0;

    // สร้างสถานีแต่ละแห่ง (หรืออัพเดตถ้ามีอยู่แล้ว)
    for (const stationData of sampleStations) {
      try {
        console.log(`\n📍 กำลังสร้าง/อัพเดตสถานี: ${stationData.stationname}`);

        // ใช้ upsertStation เพื่อสร้างใหม่หรืออัพเดตที่มีอยู่แล้ว
        const result = await stationService.upsertStation(stationData);
        const isNewStation = !result.createdAt || result.createdAt.getTime() === new Date(result.updatedAt).getTime();

        if (isNewStation) {
          console.log(
            `   ✅ สร้างสถานีสำเร็จ: ${result.stationname} (ID: ${result.id})`
          );
          totalStationsCreated++;
        } else {
          console.log(
            `   🔄 อัพเดตสถานีสำเร็จ: ${result.stationname} (ID: ${result.id})`
          );
        }

        // นับจำนวน charge points ที่สร้าง
        if (stationData.chargePoints && stationData.chargePoints.length > 0) {
          totalChargePointsCreated += stationData.chargePoints.length;
        }
      } catch (error) {
        console.error(
          `   ❌ สร้าง/อัพเดตสถานี ${stationData.stationname} ไม่สำเร็จ:`,
          error
        );
      }
    }

    console.log("\n🎉 เสร็จสิ้นการสร้าง/อัพเดตข้อมูลตัวอย่าง!");
    console.log(`📊 สรุป:`);
    console.log(`   - สร้างสถานีทั้งหมด: ${totalStationsCreated} แห่ง`);
    console.log(
      `   - สร้าง Charge Points ทั้งหมด: ${totalChargePointsCreated} ตัว`
    );
  } catch (error) {
    console.error("❌ เกิดข้อผิดพลาดในการสร้างข้อมูล:", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
    console.log("🔌 ปิดการเชื่อมต่อฐานข้อมูล");
  }
}

// รัน script
main();
